# Generated by Django 3.2.10 on 2021-12-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(null=True, upload_to='auctions/static/auctions/images/')),
            ],
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.image'),
        ),
    ]
