# Generated by Django 3.2.10 on 2021-12-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='auctions/static/auctions/images/'),
        ),
    ]
