# Generated by Django 3.2.10 on 2021-12-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='commerce/auctions/static/auctions/uploads/'),
        ),
    ]
