# Generated by Django 3.2.10 on 2022-01-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220102_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='feature1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='feature2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='feature3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='feature4',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='feature5',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
