# Generated by Django 3.2.10 on 2022-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220106_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='feature1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='feature2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='feature3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='feature4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='feature5',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
