# Generated by Django 3.2.10 on 2022-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(to='auctions.AuctionListing'),
        ),
    ]
