# Generated by Django 3.2.10 on 2022-01-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_watchlist_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Wishlist',
        ),
    ]
